### ISSUE TITLE
Migrate models to class-based for improving TypeScript compatibility.

### ISSUE THREAD

**Issue by azu** [honkit/honkit#169]
We want to migrate all models to class-based for improving TypeScript compatibility.

https://github.com/honkit/honkit/tree/master/packages/honkit/src/models

Welcome to contribute this migration!

## Migration Steps

1. migrate model file via [semgrep](https://semgrep.dev/)

Example: migrate `./src/models/book.ts` to class-based.

```
$ semgrep --config ./semgrep.yml ./src/models/book.ts --autofix
```

2. compile TypeScript and fix compile error

```
$ npm run build
# Fix compile errors
```

## TODO

If you want to contribute it, please mention it.

- [x] [book.ts](https://github.com/honkit/honkit/tree/master/packages/honkit/src/models/book.ts)
- [x] [config.ts](https://github.com/honkit/honkit/tree/master/packages/honkit/src/models/config.ts)
- [x] [file.ts](https://github.com/honkit/honkit/tree/master/packages/honkit/src/models/file.ts)
- [x] [fs.ts](https://github.com/honkit/honkit/tree/master/packages/honkit/src/models/fs.ts)
- [x] [glossary.ts](https://github.com/honkit/honkit/tree/master/packages/honkit/src/models/glossary.ts)
- [x] [glossaryEntry.ts](https://github.com/honkit/honkit/tree/master/packages/honkit/src/models/glossaryEntry.ts)
- [x] [hash.ts](https://github.com/honkit/honkit/tree/master/packages/honkit/src/models/hash.ts)
- [x] [ignore.ts](https://github.com/honkit/honkit/tree/master/packages/honkit/src/models/ignore.ts)
- [x] [language.ts](https://github.com/honkit/honkit/tree/master/packages/honkit/src/models/language.ts)
- [x] [languages.ts](https://github.com/honkit/honkit/tree/master/packages/honkit/src/models/languages.ts)
- [x] [output.ts](https://github.com/honkit/honkit/tree/master/packages/honkit/src/models/output.ts)
- [x] [page.ts](https://github.com/honkit/honkit/tree/master/packages/honkit/src/models/page.ts)
- [x] [parser.ts](https://github.com/honkit/honkit/tree/master/packages/honkit/src/models/parser.ts)
- [x] [plugin.ts](https://github.com/honkit/honkit/tree/master/packages/honkit/src/models/plugin.ts)
- [x] [pluginDependency.ts](https://github.com/honkit/honkit/tree/master/packages/honkit/src/models/pluginDependency.ts)
- [x] [readme.ts](https://github.com/honkit/honkit/tree/master/packages/honkit/src/models/readme.ts)
- [x] [summary.ts](https://github.com/honkit/honkit/tree/master/packages/honkit/src/models/summary.ts)
- [x] [summaryArticle.ts](https://github.com/honkit/honkit/tree/master/packages/honkit/src/models/summaryArticle.ts)
- [x] [summaryPart.ts](https://github.com/honkit/honkit/tree/master/packages/honkit/src/models/summaryPart.ts)
- [x] [templateBlock.ts](https://github.com/honkit/honkit/tree/master/packages/honkit/src/models/templateBlock.ts)
- [x] [templateEngine.ts](https://github.com/honkit/honkit/tree/master/packages/honkit/src/models/templateEngine.ts)
- [x] [templateOutput.ts](https://github.com/honkit/honkit/tree/master/packages/honkit/src/models/templateOutput.ts)
- [x] [templateShortcut.ts](https://github.com/honkit/honkit/tree/master/packages/honkit/src/models/templateShortcut.ts)

## Examples

- migrate book.ts to class-based immutable model #165
- migrate config.ts to class-based #166

_Originally posted by @azu in https://github.com/honkit/honkit/issues/40#issuecomment-735355945_

**Comment by azu** [comment]
Complet Migration!
