### ISSUE TITLE
Docker: Update to node:16

### ISSUE THREAD

**Issue by azu** [honkit/honkit#290]
I think we need to raise the base image to at least node 16.
It will be major release and honkit@4 image use node 16 and drop to support node 12.
It means that If user want to use node 12, the user need to use honkit@3 image.

_Originally posted by @azu in https://github.com/honkit/honkit/issues/288#issuecomment-1229200705_

## TODO

- [ ] Drop to support Node.js 12
  - https://github.com/honkit/honkit/blob/749bff26a7695cac0c8eca795a30537267166b8d/.github/workflows/test.yml#L13-L20
  - 14, 16, 18 will test matrix
  - [ ] use ubuntu-latest
- [x] update node:12 to node:16 in Dockerfile #289
