### ISSUE TITLE
Rename GitHon to HonKit

### ISSUE THREAD

**Issue by azu** [honkit/honkit#52]
Acording to #48, `Git` is trandmark 

- [About - Git](https://www.git-scm.com/about/trademark)

So, we need to rename GitHon project.

Edit: 

We have decided to rename GItHon to HonKit.

## Todo

- [x] GitHub Organization
- [x] Netlify https://honkit.netlify.app/
- [x] Source Code & package.json
- [x] Documents
- [x] npm
  - [ ] maybe deperecated old name #54 
- [x] Blog
  - https://efcl.info/2020/06/19/githon/

## User Affects

Probably, https://github.com/githon/ is 404.

- npm package is still aliave

**Comment by azu** [comment]
OK. Test and https://githon.netlify.app/ is live.
Start to migrate `GitHon` → `HonKit` (honkit).

**Comment by azu** [comment]
- [x] https://github.com/HonKit

**Comment by azu** [comment]
- [x] https://github.com/HonKit/HonKit

**Comment by azu** [comment]
- [x] Get new home! https://honkit.netlify.app/

**Comment by azu** [comment]
```
transfer-github-owner --from githon --to honkit
./node_modules/.bin/lerna exec -- transfer-github-owner --from githon --to honkit
```

https://github.com/azu/transfer-github-owner

**Comment by azu** [comment]
Get new npm org https://www.npmjs.com/~honkit

**Comment by azu** [comment]
> Source Code & package.json

PR #53

**Comment by azu** [comment]
I've tried to release new name `honkit` for testing.

**Comment by azu** [comment]
Successfully published:
 - honkit@3.3.10
 - @honkit/asciidoc@3.3.8
 - @honkit/html@3.3.8
 - @honkit/markdown@3.3.8
 - @honkit/markup-it@3.3.8
 - @honkit/honkit-plugin-theme-default@3.3.9

**Comment by azu** [comment]
repost https://efcl.info/2020/06/19/githon/

**Comment by azu** [comment]
We have get new Project name: **HonKit** 🎉 

Thanks to people on GitHub/Twitter.
